spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/ecommerce-member;MODE=MySQL;NON_KEYWORDS=value;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        globally_quoted_identifiers: true
#        globally_quoted_identifiers_skip_column_definitions: true
        show_sql: true
        format_sql:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  cloud:
    vault:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    enabled: false
