spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/ecommerce-member;MODE=MySQL;NON_KEYWORDS=value;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema-h2.sql
        - classpath:sql/data.sql

  cloud:
    vault:
      enabled: false

  data:
    redis:
      port: 6379
      host: 127.0.0.1

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    enabled: false
