version: '3'
services:
  product-service:
    image: msafriend/ecommerce-service-product:latest
    networks:
      - msafriends_network
    depends_on:
      product-mysql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8020:8080"

  product-mysql:
    image: mysql:8.0
    networks:
      - msafriends_network
    volumes:
      - ./.docker/product-service/db/conf.d:/etc/mysql/conf.d
      - ./.docker/product-service/db/data:/var/lib/mysql
      - ./.docker/product-service/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ecommerce-product
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 20s
      timeout: 10s
      retries: 10

networks:
  msafriends_network:
    driver: bridge
