
spring:
  application:
    name: order-service
  config:
    import: vault://
  cloud:
    vault:
      authentication: TOKEN
      uri: https://vault.binarybard.kr
      token: ${VAULT_TOKEN}
      kv:
        backend: ecommerce
        application-name: ${spring.application.name}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces