spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem://localhost/ecommerce-order;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  cloud:
    vault:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug