spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
  batch:
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        globally_quoted_identifiers: true
        #        globally_quoted_identifiers_skip_column_definitions: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema-mysql.sql

  cloud:
    vault:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    enabled: false
cloud:
  aws:
    s3:
      bucket: ${s3.bucket}
    credentials:
      access-key: ${s3.accesskey}
      secret-key: ${s3.secretkey}

    region:
      static: ${s3.region}
    stack:
      auto: false
images:
  path: ${s3.images.dir}