
spring:
  application:
    name: product-service
  config:
    import: vault://
    activate:
      on-profile: "prod"
  cloud:
    vault:
      authentication: TOKEN
      uri: https://vault.binarybard.kr
      token: ${VAULT_TOKEN}
      kv:
        backend: ecommerce
        application-name: ${spring.application.name}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://13.125.53.32:8761
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces