spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: Rkaodwja6^
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        globally_quoted_identifiers: true
        #        globally_quoted_identifiers_skip_column_definitions: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema-mysql.sql

  cloud:
    vault:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  client:
    enabled: false